# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Edward Wisniewski
email: hello@edwerd.co
tagline: Designer by day, developer by night
description: > # this means to ignore newlines until "baseurl:"
  Designer by day, developer by night
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://edwerd.co" # the base hostname & protocol for your site
twitter_username: edwerd
github_username:  edwerd
dribbble_username: edwerd
collections:
  projects:
    output: true

# Build settings
markdown: kramdown
